### ISSUE TITLE
TODO Before Launch

### ISSUE THREAD

**Issue by jamesjulich** [Badger-Spill/badger-spill.github.io#1]
This is a todo list for the frontend before launching the new Badger Spill website.

- [x] Add a get involved page
- [x] Write Javascript to handle the forms
- [ ] Add some sort of contact button or email address
- [ ] Refactor resources page to expand via columns instead of rows
- [x] Optimize images
- [ ] Add vertical space between Badger Spill logo and navlinks on < small displays to fufill  Pagespeeds requirement
